import {db} from '../config/firebase.js';import {getLocalDate,isExpired,isBeforeStart,addDays} from '../utils/date.js';import {calculateDayStats} from '../utils/stats.js';
export async function getChecklistRef(uid,date){return db.collection('dailyChecklists').doc(`${uid}_${date}`)}
export async function generateForUser(uid,date=getLocalDate()){const ref=await getChecklistRef(uid,date);const existing=await ref.get();if(existing.exists){const items=await ref.collection('items').get();return {id:ref.id,...existing.data(),items:items.docs.map(d=>({id:d.id,...d.data()}))}}
const day=new Intl.DateTimeFormat('en-US',{timeZone:process.env.DEFAULT_TIME_ZONE||'Africa/Douala',weekday:'long'}).format(new Date(`${date}T12:00:00Z`)).toUpperCase();const schedules=await db.collection('schedules').where('userId','==',uid).where('active','==',true).get();const selected=schedules.docs.map(d=>({id:d.id,...d.data()})).filter(s=>s.days.includes(day)).sort((a,b)=>a.startTime.localeCompare(b.startTime));const batch=db.batch();const now=new Date().toISOString();batch.set(ref,{userId:uid,date,totalActivities:selected.length,completedActivities:0,missedActivities:0,completionRate:0,dayStatus:selected.length?'YELLOW':'NEUTRAL',createdAt:now,updatedAt:now});for(const s of selected){const item=ref.collection('items').doc(s.id);batch.set(item,{scheduleId:s.id,userId:uid,date,title:s.title,startTime:s.startTime,endTime:s.endTime,status:'PENDING',type:'SCHEDULED',completedAt:null,missedAt:null,makeupCreated:false,createdAt:now})}await batch.commit();return {id:ref.id,userId:uid,date,totalActivities:selected.length,completedActivities:0,missedActivities:0,completionRate:0,dayStatus:selected.length?'YELLOW':'NEUTRAL',items:selected.map(s=>({id:s.id,scheduleId:s.id,userId:uid,date,title:s.title,startTime:s.startTime,endTime:s.endTime,status:'PENDING',type:'SCHEDULED',completedAt:null,missedAt:null,makeupCreated:false}))}}
export async function readChecklist(uid,date){const ref=await getChecklistRef(uid,date),snap=await ref.get();if(!snap.exists)return generateForUser(uid,date);const items=(await ref.collection('items').get()).docs.map(d=>({id:d.id,...d.data()}));return {id:ref.id,...snap.data(),items:items.sort((a,b)=>a.startTime.localeCompare(b.startTime))}}
async function createMakeup(uid,missedItem){if(missedItem.type==='MAKEUP'||missedItem.makeupCreated)return;const dt=new Date(`${missedItem.date}T12:00:00Z`),dow=dt.getUTCDay();if(dow===6||dow===0)return;const saturday=addDays(missedItem.date,6-dow);const ref=await getChecklistRef(uid,saturday);const snap=await ref.get();if(!snap.exists)await generateForUser(uid,saturday);const itemsSnap=await ref.collection('items').get();let start=600;for(const i of itemsSnap.docs.map(d=>d.data())){const end=Number(i.endTime.slice(0,2))*60+Number(i.endTime.slice(3));if(end>start)start=end}const toMin=t=>Number(t.slice(0,2))*60+Number(t.slice(3)); const dur=Math.max(30,toMin(missedItem.endTime)-toMin(missedItem.startTime));const end=Math.min(23*60+59,start+dur);const pad=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');const itemRef=ref.collection('items').doc(`makeup_${missedItem.id}`);await itemRef.set({scheduleId:null,userId:uid,date:saturday,title:`Rattrapage : ${missedItem.title}`,startTime:pad(start),endTime:pad(end),status:'PENDING',type:'MAKEUP',originalActivityId:missedItem.id,originalDate:missedItem.date,completedAt:null,missedAt:null,makeupCreated:false,createdAt:new Date().toISOString()});await db.collection('dailyChecklists').doc(`${uid}_${missedItem.date}`).collection('items').doc(missedItem.id).update({makeupCreated:true})}
export async function reconcileUser(uid,now=new Date()){const snap=await db.collection('dailyChecklists').where('userId','==',uid).get();for(const d of snap.docs){const data=d.data();for(const itemDoc of (await d.ref.collection('items').where('status','==','PENDING').get()).docs){const item=itemDoc.data();if(isExpired(item.date,item.endTime,now)){await itemDoc.ref.update({status:'MISSED',missedAt:now.toISOString()});await createMakeup(uid,{id:itemDoc.id,...item})}}await refreshStats(d.ref)}}
export async function refreshStats(ref){const items=(await ref.collection('items').get()).docs.map(d=>d.data());const s=calculateDayStats(items);await ref.update({totalActivities:s.total,completedActivities:s.completed,missedActivities:s.missed,completionRate:s.completionRate,dayStatus:s.dayStatus,updatedAt:new Date().toISOString()});return s}
export async function completeItem(uid,date,itemId){const ref=await getChecklistRef(uid,date),itemRef=ref.collection('items').doc(itemId),snap=await itemRef.get();if(!snap.exists)return {status:404,error:'Activité introuvable'};const item=snap.data();if(item.userId!==uid)return {status:403,error:'Accès refusé'};if(item.status!=='PENDING')return {status:409,error:'Cette activité est déjà terminée ou expirée.'};if(isBeforeStart(item.date,item.startTime,new Date()))return {status:409,error:'Cette activité n’a pas encore commencé.'};if(isExpired(item.date,item.endTime,new Date()))return {status:409,error:'Impossible de valider cette activité : son temps est déjà terminé.'};await itemRef.update({status:'COMPLETED',completedAt:new Date().toISOString()});await refreshStats(ref);return {status:200,data:await readChecklist(uid,date)}}
export async function reconcileAll(){const users=await db.collection('users').get();for(const u of users.docs)await reconcileUser(u.id)}
export async function generateAll(){const users=await db.collection('users').get(),date=getLocalDate();for(const u of users.docs)await generateForUser(u.id,date)}
